import React, { useState } from "react";
import { Settings as SettingsIcon, Cpu, Mic, Brain, Shield, Trash2, CheckCircle2, RefreshCw } from "lucide-react";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Switch } from "@/components/ui/switch";
import { Button } from "@/components/ui/button";
import { getSettings, saveSettings } from "@/services/settingsService";
import { fetchMemories, deleteMemory } from "@/lib/api";

export function SettingsPage() {
  const [settings, setSettingsState] = useState(getSettings());
  const [clearing, setClearing] = useState(false);

  const handleToggle = (section, key) => {
    const updated = {
      ...settings,
      [section]: {
        ...settings[section],
        [key]: !settings[section][key],
      },
    };
    setSettingsState(updated);
    saveSettings(updated);
  };

  const handleClearAllMemories = async () => {
    if (!confirm("Are you sure you want to clear all stored memories and active conditions from SQLite?")) return;
    setClearing(true);
    const data = await fetchMemories();
    if (data.memories) {
      for (const m of data.memories) {
        await deleteMemory(m.key);
      }
    }
    setClearing(false);
    alert("All memories have been cleared from SQLite memory.db!");
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6 py-2 animate-in fade-in-50 duration-300">
      {/* Header Bar */}
      <div>
        <h1 className="text-xl font-semibold font-sans tracking-tight text-zinc-100 flex items-center gap-2">
          <SettingsIcon className="w-5 h-5 text-zinc-300" />
          Settings & Engine Controls
        </h1>
        <p className="text-xs text-zinc-400 font-sans mt-0.5">
          Active system configuration for local LLM inference, wake word, memory engine, and telemetry.
        </p>
      </div>

      <Tabs defaultValue="ai" className="w-full">
        <TabsList className="grid grid-cols-3 md:grid-cols-5 w-full bg-zinc-950 border border-zinc-800 p-1 h-auto">
          <TabsTrigger value="ai" className="text-xs font-mono py-1.5">AI Engine</TabsTrigger>
          <TabsTrigger value="voice" className="text-xs font-mono py-1.5">Voice</TabsTrigger>
          <TabsTrigger value="memory" className="text-xs font-mono py-1.5">Memory Engine</TabsTrigger>
          <TabsTrigger value="privacy" className="text-xs font-mono py-1.5">Privacy</TabsTrigger>
          <TabsTrigger value="telemetry" className="text-xs font-mono py-1.5">Telemetry</TabsTrigger>
        </TabsList>

        {/* AI Settings Tab */}
        <TabsContent value="ai" className="space-y-4 pt-4">
          <Card className="bg-zinc-950/70 border-zinc-800 p-4 rounded-xl space-y-4">
            <h3 className="text-xs font-mono text-zinc-400 font-semibold uppercase tracking-wider">
              LLM Model & Streaming Parameters
            </h3>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs font-mono">
              <div className="p-3 bg-zinc-900/60 border border-zinc-800 rounded-lg space-y-1">
                <span className="text-zinc-500">Active Model</span>
                <p className="text-zinc-100 font-semibold">{settings.ai.model}</p>
              </div>

              <div className="p-3 bg-zinc-900/60 border border-zinc-800 rounded-lg space-y-1">
                <span className="text-zinc-500">Inference Backend</span>
                <p className="text-zinc-100 font-semibold">{settings.ai.backend} ({settings.ai.acceleration})</p>
              </div>
            </div>

            <div className="space-y-3 pt-2">
              <div className="flex items-center justify-between">
                <div>
                  <h4 className="text-xs font-sans font-medium text-zinc-200">Real-Time SSE Token Streaming</h4>
                  <p className="text-[11px] font-sans text-zinc-500">Streams tokens live as generated by LLM</p>
                </div>
                <Switch
                  checked={settings.ai.streaming}
                  onCheckedChange={() => handleToggle("ai", "streaming")}
                />
              </div>
            </div>
          </Card>
        </TabsContent>

        {/* Voice Tab */}
        <TabsContent value="voice" className="space-y-4 pt-4">
          <Card className="bg-zinc-950/70 border-zinc-800 p-4 rounded-xl space-y-4">
            <h3 className="text-xs font-mono text-zinc-400 font-semibold uppercase tracking-wider">
              Speech Dictation & Wake Word
            </h3>

            <div className="space-y-3 text-xs">
              <div className="flex items-center justify-between pb-3 border-b border-zinc-800/60">
                <div>
                  <h4 className="text-xs font-sans font-medium text-zinc-200">Hands-Free Wake Word ("Hey JARVIS")</h4>
                  <p className="text-[11px] font-sans text-zinc-500">Background wake word engine listener</p>
                </div>
                <Switch
                  checked={settings.voice.wakeWordEnabled}
                  onCheckedChange={() => handleToggle("voice", "wakeWordEnabled")}
                />
              </div>

              <div className="flex items-center justify-between pt-1">
                <div>
                  <h4 className="text-xs font-sans font-medium text-zinc-200">Auto Speak Responses</h4>
                  <p className="text-[11px] font-sans text-zinc-500">Speak AI output via macOS TTS</p>
                </div>
                <Switch
                  checked={settings.voice.autoSpeak}
                  onCheckedChange={() => handleToggle("voice", "autoSpeak")}
                />
              </div>
            </div>
          </Card>
        </TabsContent>

        {/* Memory Tab */}
        <TabsContent value="memory" className="space-y-4 pt-4">
          <Card className="bg-zinc-950/70 border-zinc-800 p-4 rounded-xl space-y-4">
            <h3 className="text-xs font-mono text-zinc-400 font-semibold uppercase tracking-wider">
              SQLite Memory Engine & Extraction Controls
            </h3>

            <div className="space-y-3 text-xs">
              <div className="flex items-center justify-between pb-3 border-b border-zinc-800/60">
                <div>
                  <h4 className="text-xs font-sans font-medium text-zinc-200">Automatic LLM Memory Extraction</h4>
                  <p className="text-[11px] font-sans text-zinc-500">Extracts facts and health conditions from chat turns</p>
                </div>
                <Switch
                  checked={settings.memory.autoExtraction}
                  onCheckedChange={() => handleToggle("memory", "autoExtraction")}
                />
              </div>

              <div className="flex items-center justify-between pt-2">
                <div>
                  <h4 className="text-xs font-sans font-medium text-zinc-200">Clear All Stored Memories</h4>
                  <p className="text-[11px] font-sans text-zinc-500">Purges all facts and active conditions from SQLite memory.db</p>
                </div>
                <Button
                  onClick={handleClearAllMemories}
                  disabled={clearing}
                  variant="outline"
                  size="sm"
                  className="border-red-900/60 bg-red-950/40 text-red-300 hover:bg-red-900/60 text-xs font-mono gap-1"
                >
                  <Trash2 className="w-3.5 h-3.5" />
                  <span>{clearing ? "Clearing..." : "Clear Memories"}</span>
                </Button>
              </div>
            </div>
          </Card>
        </TabsContent>

        {/* Privacy Tab */}
        <TabsContent value="privacy" className="space-y-4 pt-4">
          <Card className="bg-zinc-950/70 border-zinc-800 p-4 rounded-xl space-y-4">
            <div className="flex items-center justify-between pb-2 border-b border-zinc-800">
              <div className="flex items-center gap-2">
                <Shield className="w-4 h-4 text-emerald-400" />
                <h3 className="text-xs font-mono text-zinc-200 font-semibold uppercase tracking-wider">
                  Local Processing & Security
                </h3>
              </div>
              <Badge className="bg-emerald-950/50 text-emerald-400 border border-emerald-900/50 font-mono text-[10px]">
                100% PRIVATE & LOCAL
              </Badge>
            </div>

            <div className="space-y-2 text-xs font-mono">
              <div className="flex items-center justify-between p-2.5 bg-zinc-900/60 rounded-lg">
                <span>Local AI Processing</span>
                <span className="text-emerald-400">ENABLED</span>
              </div>
              <div className="flex items-center justify-between p-2.5 bg-zinc-900/60 rounded-lg">
                <span>Cloud Data Telemetry</span>
                <span className="text-zinc-500">OFF</span>
              </div>
              <div className="flex items-center justify-between p-2.5 bg-zinc-900/60 rounded-lg">
                <span>External Analytics</span>
                <span className="text-zinc-500">OFF</span>
              </div>
            </div>
          </Card>
        </TabsContent>

        {/* Telemetry & Diagnostic Tab */}
        <TabsContent value="telemetry" className="space-y-4 pt-4">
          <Card className="bg-zinc-950/70 border-zinc-800 p-4 rounded-xl space-y-4">
            <h3 className="text-xs font-mono text-zinc-400 font-semibold uppercase tracking-wider">
              JARVIS Execution Pipeline Diagram
            </h3>

            <div className="p-4 bg-zinc-900/80 border border-zinc-800/80 rounded-xl font-mono text-xs text-center space-y-3">
              <div className="flex flex-wrap items-center justify-center gap-2 text-zinc-300">
                <span className="p-2 bg-zinc-950 border border-zinc-800 rounded-lg">Voice / Input</span>
                <span>→</span>
                <span className="p-2 bg-zinc-950 border border-zinc-800 rounded-lg">Faster-Whisper</span>
                <span>→</span>
                <span className="p-2 bg-zinc-950 border border-zinc-800 rounded-lg">Router</span>
                <span>→</span>
                <span className="p-2 bg-zinc-950 border border-zinc-800 rounded-lg">SQLite Memory</span>
                <span>→</span>
                <span className="p-2 bg-zinc-950 border border-zinc-800 rounded-lg">Qwen3 LLM</span>
                <span>→</span>
                <span className="p-2 bg-zinc-950 border border-zinc-800 rounded-lg">macOS TTS</span>
              </div>
            </div>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}
